// user events
export const USER_REGISTERED = "USER_REGISTERED";
export const USER_APPROVED_AS_ORGANIZER = "USER_APPROVED_AS_ORGANIZER";

// application events
export const APPLICATION_APPROVED = "APPLICATION_APPROVED";
export const APPLICATION_REJECTED = "APPLICATION_REJECTED";
export const APPLICATION_PERMANENTLY_REJECTED =
  "APPLICATION_PERMANENTLY_REJECTED";

// booking events
export const RESERVATION_CREATED = "RESERVATION_CREATED";
export const RESERVATION_EXPIRED = "RESERVATION_EXPIRED";
export const RESERVATION_CANCELLED = "RESERVATION_CANCELLED";

// payment events
export const PAYMENT_SUCCEEDED = "PAYMENT_SUCCEEDED";
export const PAYMENT_FAILED = "PAYMENT_FAILED";
export const PAYMENT_CANCELED = "PAYMENT_CANCELED";
export const PAYMENT_EXPIRED = "PAYMENT_EXPIRED";
export const PAYMENT_STATUS_UPDATED = "PAYMENT_STATUS_UPDATED";

// Ticket Types
export const TICKET_TYPE_CREATED = "TICKET_TYPE_CREATED";
export const TICKET_TYPE_UPDATED = "TICKET_TYPE_UPDATED";
export const TICKET_TYPE_DELETED = "TICKET_TYPE_DELETED";
export const TICKET_ISSUED = "TICKET_ISSUED";
export const TICKET_CANCELLED = "TICKET_CANCELLED";
export const TICKET_CHECKED_IN = "TICKET_CHECKED_IN";
export const TICKET_CHECK_IN_REVERSED = "TICKET_CHECK_IN_REVERSED";

// Events' event
export const EVENT_CANCELLED = "EVENT_CANCELLED";
export const EVENT_PUBLISHED = "EVENT_PUBLISHED";

// Attendee events
export const ATTENDEE_CREATED = "ATTENDEE_CREATED";

export const AVAILABILITY_CHANGED = "AVAILABILITY_CHANGED";
export const AVAILABILITY_SOLD_OUT = "AVAILABILITY_SOLD_OUT";
export const AVAILABILITY_RESTOCKED = "AVAILABILITY_RESTOCKED";
