// user events
export const USER_REGISTERED = "USER_REGISTERED";
export const USER_APPROVED_AS_ORGANIZER = "USER_APPROVED_AS_ORGANIZER";

// application events
export const APPLICATION_APPROVED = "APPLICATION_APPROVED";
export const APPLICATION_REJECTED = "APPLICATION_REJECTED";
export const APPLICATION_PERMANENTLY_REJECTED =
  "APPLICATION_PERMANENTLY_REJECTED";

// booking events
export const BOOKING_CREATED = "BOOKING_CREATED";
export const BOOKING_CANCELLED = "BOOKING_CANCELLED";

// payment events
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAILED = "PAYMENT_FAILED";
