// user events
export const USER_REGISTERED = "USER_REGISTERED";
export const USER_APPROVED_AS_ORGANIZER = "USER_APPROVED_AS_ORGANIZER";

// application events
export const APPLICATION_APPROVED = "APPLICATION_APPROVED";
export const APPLICATION_REJECTED = "APPLICATION_REJECTED";
export const APPLICATION_PERMANENTLY_REJECTED =
  "APPLICATION_PERMANENTLY_REJECTED";

// booking events
export const BOOKING_CREATED = "BOOKING_CREATED";
export const BOOKING_CANCELLED = "BOOKING_CANCELLED";

// payment events
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAILED = "PAYMENT_FAILED";

// Ticket Types
export const TICKET_TYPE_CREATED = "TICKET_TYPE_CREATED";
export const TICKET_TYPE_UPDATED = "TICKET_TYPE_UPDATED";
export const TICKET_TYPE_DELETED = "TICKET_TYPE_DELETED";
export const TICKET_ISSUED = "TICKET_ISSUED";
export const TICKET_CANCELLED = "TICKET_CANCELLED";
export const TICKET_CHECKED_IN = "TICKET_CHECKED_IN";
export const TICKET_CHECK_IN_REVERSED = "TICKET_CHECK_IN_REVERSED";
