import { ORGANIZER_STATUS } from "../enums/organizer-status";
import ROLE from "../enums/role";
import { Organizer } from "./organizer.schema";
import { categories } from "@/constants/categories";

export const mockOrganizers: Organizer[] = [
  {
    organizerId: "org_123",
    organizerStatus: ORGANIZER_STATUS.APPROVED,
    followersCount: 1200,
    eventsCount: 15,
    bio: "Tổ chức các sự kiện âm nhạc chất lượng cao tại Sài Gòn",
    email: "saigonmusic@example.com",
    phoneNumber: "+84123456789",
    photoUrl:
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=150&h=150&fit=crop&crop=face",
    role: ROLE.EVENT_ORGANIZER,
    username: "Saigon Music Events",
    websiteUrl: "https://www.saigonmusic.com",
    facebookUrl: "https://www.facebook.com/saigonmusic",
    instagramUrl: "https://www.instagram.com/saigonmusic",
    xUrl: "https://www.x.com/saigonmusic",
    categories: [
      categories.find((c) => c.id === "music")!,
      categories.find((c) => c.id === "festival")!,
    ],
  },
  {
    organizerId: "org_123457",
    organizerStatus: ORGANIZER_STATUS.APPROVED,
    followersCount: 890,
    eventsCount: 12,
    bio: "Hội thảo và sự kiện công nghệ hàng đầu Việt Nam",
    email: "techconf@example.com",
    phoneNumber: "+84123456790",
    photoUrl:
      "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=150&h=150&fit=crop",
    role: ROLE.EVENT_ORGANIZER,
    username: "Tech Conference Vietnam",
    websiteUrl: "https://www.techconf.vn",
    facebookUrl: "https://www.facebook.com/techconfvn",
    instagramUrl: "https://www.instagram.com/techconfvn",
    xUrl: "https://www.x.com/techconfvn",
    categories: [
      categories.find((c) => c.id === "tech")!,
      categories.find((c) => c.id === "conference")!,
    ],
  },
  {
    organizerId: "org_123458",
    organizerStatus: ORGANIZER_STATUS.APPROVED,
    followersCount: 650,
    eventsCount: 8,
    bio: "Lễ hội ẩm thực và trải nghiệm văn hóa ẩm thực",
    email: "foodiefest@example.com",
    phoneNumber: "+84123456791",
    photoUrl:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=150&h=150&fit=crop",
    role: ROLE.EVENT_ORGANIZER,
    username: "Foodie Festival Co.",
    websiteUrl: "https://www.foodiefest.com",
    facebookUrl: "https://www.facebook.com/foodiefest",
    instagramUrl: "https://www.instagram.com/foodiefest",
    xUrl: "https://www.x.com/foodiefest",
    categories: [
      categories.find((c) => c.id === "food")!,
      categories.find((c) => c.id === "festival")!,
    ],
  },
  {
    organizerId: "org_123459",
    organizerStatus: ORGANIZER_STATUS.APPROVED,
    followersCount: 2100,
    eventsCount: 25,
    bio: "Triển lãm nghệ thuật và các sự kiện văn hóa",
    email: "artgallery@example.com",
    phoneNumber: "+84123456792",
    photoUrl:
      "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=150&h=150&fit=crop",
    role: ROLE.EVENT_ORGANIZER,
    username: "Art Gallery Hanoi",
    websiteUrl: "https://www.artgalleryhanoi.com",
    facebookUrl: "https://www.facebook.com/artgalleryhanoi",
    instagramUrl: "https://www.instagram.com/artgalleryhanoi",
    xUrl: "https://www.x.com/artgalleryhanoi",
    categories: [
      categories.find((c) => c.id === "art")!,
      categories.find((c) => c.id === "exhibition")!,
    ],
  },
  {
    organizerId: "org_123410",
    organizerStatus: ORGANIZER_STATUS.APPROVED,
    followersCount: 980,
    eventsCount: 18,
    bio: "Tổ chức các giải đấu và sự kiện thể thao",
    email: "sportsarena@example.com",
    phoneNumber: "+84123456793",
    photoUrl:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=150&h=150&fit=crop",
    role: ROLE.EVENT_ORGANIZER,
    username: "Sports Arena VN",
    websiteUrl: "https://www.sportsarena.vn",
    facebookUrl: "https://www.facebook.com/sportsarenavn",
    instagramUrl: "https://www.instagram.com/sportsarenavn",
    xUrl: "https://www.x.com/sportsarenavn",
    categories: [
      categories.find((c) => c.id === "sports")!,
      categories.find((c) => c.id === "competition")!,
    ],
  },
  {
    organizerId: "org_123411",
    organizerStatus: ORGANIZER_STATUS.APPROVED,
    followersCount: 750,
    eventsCount: 10,
    bio: "Hội thảo kinh doanh và kết nối doanh nghiệp",
    email: "businesssummit@example.com",
    phoneNumber: "+84123456794",
    photoUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    role: ROLE.EVENT_ORGANIZER,
    username: "Business Summit Asia",
    websiteUrl: "https://www.businesssummit.asia",
    facebookUrl: "https://www.facebook.com/businesssummitasia",
    instagramUrl: "https://www.instagram.com/businesssummitasia",
    xUrl: "https://www.x.com/businesssummitasia",
    categories: [
      categories.find((c) => c.id === "business")!,
      categories.find((c) => c.id === "networking")!,
    ],
  },
  {
    organizerId: "org_123452",
    organizerStatus: ORGANIZER_STATUS.APPROVED,
    followersCount: 1100,
    eventsCount: 22,
    bio: "Tổ chức các lễ hội văn hóa và sự kiện đặc biệt",
    email: "festivalmasters@example.com",
    phoneNumber: "+84123456795",
    photoUrl:
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=150&h=150&fit=crop",
    role: ROLE.EVENT_ORGANIZER,
    username: "Festival Masters",
    websiteUrl: "https://www.festivalmasters.com",
    facebookUrl: "https://www.facebook.com/festivalmasters",
    instagramUrl: "https://www.instagram.com/festivalmasters",
    xUrl: "https://www.x.com/festivalmasters",
    categories: [
      categories.find((c) => c.id === "festival")!,
      categories.find((c) => c.id === "party")!,
    ],
  },
  {
    organizerId: "org_123453",
    organizerStatus: ORGANIZER_STATUS.APPROVED,
    followersCount: 450,
    eventsCount: 6,
    bio: "Chuyên tổ chức các workshop và khóa học kỹ năng",
    email: "workshoppro@example.com",
    phoneNumber: "+84123456796",
    photoUrl:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=150&h=150&fit=crop",
    role: ROLE.EVENT_ORGANIZER,
    username: "Workshop Pro",
    websiteUrl: "https://www.workshoppro.com",
    facebookUrl: "https://www.facebook.com/workshoppro",
    instagramUrl: "https://www.instagram.com/workshoppro",
    xUrl: "https://www.x.com/workshoppro",
    categories: [
      categories.find((c) => c.id === "workshop")!,
      categories.find((c) => c.id === "training")!,
    ],
  },
];

export const mockOrganizer: Organizer = mockOrganizers[0];
