export const EVENT_TYPES = {
  USER_CREATED: "USER_CREATED",
  USER_DELETED: "USER_DELETED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  APPLICATION_APPROVED: "APPLICATION_APPROVED",
  APPLICATION_REJECTED: "APPLICATION_REJECTED",
  APPLICATION_CANCELLED: "APPLICATION_CANCELLED",
  APPLICATION_STATUS_CHANGED: "APPLICATION_STATUS_CHANGED",
};
