FROM node:22-alpine

# 1️⃣ Tạo thư mục làm việc gốc
WORKDIR /app

# 2️⃣ Copy package.json chính & shared & service
COPY package*.json ./
COPY shared/package*.json ./shared/
COPY notification/package*.json ./notification/

# 4️⃣ Làm việc trong thư mục notification
WORKDIR /app/notification
# 5️⃣ Tắt husky, cài dependencies của service
ENV HUSKY=0
RUN npm install --omit=dev

# 3️⃣ Copy source code shared và service vào đúng vị trí
COPY shared/ ./shared/
COPY notification/ ./notification/


# 6️⃣ Expose port & Run app
EXPOSE 3000
CMD ["npm", "run", "start"]
