name: CI - Monorepo Full Check

on:
  pull_request:
    branches: [develop, staging, main]
  push:
    branches: [main]

jobs:
  install-deps:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install root dependencies (if any)
        run: npm install
        continue-on-error: true

  lint-and-test:
    name: Lint & Test All Services
    needs: install-deps
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [auth, ticket, payment, notification, event, analysis]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install
        working-directory: services/${{ matrix.service }}

      - name: Run Lint
        run: npm run lint
        working-directory: services/${{ matrix.service }}

      - name: Run Tests
        run: npm test
        working-directory: services/${{ matrix.service }}
