module.exports = {
    collection: "submission_documents",
    fields: {
        documentID: String,
        type: DOCUMENT_TYPE,
        submissionID: String,
        userID: String,
        fileName: String,
        imageUrl: String,
        submissionStatus: SUBMISSION_STATUS,
        metadata: {
            ownerName: String,
            dob: String,
            addresses: String,
            ethnicGroup: String,
            gender: String,
            nationality: String,
            companyName: String | null,
            shortCompanyName: String | null,
            companyNameInEnglish: String | null,
            authorizedCaptical: {
                unit: String,
                value: Number,
            },
            issuedDate: Date,
            placeOfIssue: String,
        },
        status: DOCUMENT_STATUS,
        attempts: Number,
        blocked: Boolean,
        notes: String,
        createdAt: Date,
        updatedAt: Date,
    },
};
